class StatementPdf < Prawn::Document

  def initialize(statement)
    super(page_size: "A4", margin: 40)

    @statement = statement
    @contractor = statement.contractor

    header
    contractor_info
    period_info
    invoices_table
    payments_table 
    summary_box
    footer
  end

  # ================= HEADER =================
  def header
  logo_path = Rails.root.join("app/assets/images/logo.png")

  bounding_box([0, cursor], width: bounds.width) do

    # ================= TOP ROW =================
    if File.exist?(logo_path)
      image logo_path, width: 80, position: :left
    end

    bounding_box([100, cursor + 70], width: 350) do
      text "Momak Technologies Ltd",
           size: 16,
           style: :bold

      text "Al Bustani, Kilimani, Nairobi"
      text "Tel: 0111555749"
      text "Email: info@momaktech.com"
    end
  end

  move_down 15
  stroke_horizontal_rule
  move_down 10

  # ================= TITLE =================
  text "STATEMENT",
       size: 22,
       style: :bold,
       align: :center

  move_down 5
  text "Account Statement Report",
       size: 10,
       align: :center,
       color: "666666"

  move_down 15
end
  # ================= CONTRACTOR =================
  def contractor_info
    text "Billed To:", style: :bold
    text @contractor.name
    text @contractor.location
    text @contractor.phone
    move_down 15
  end


  def payments_table
  move_down 10
  text "Payments", style: :bold
  move_down 8

  data = [["Date", "Reference", "Amount"]]

  payments.each do |p|
    data << [
      p.payment_date,
      p.reference || "N/A",
      format_currency(p.amount)
    ]
  end

  if payments.empty?
    data << ["No payments found", "", ""]
  end

  table(data, header: true, width: bounds.width) do
    row(0).font_style = :bold
    row(0).background_color = "E8F5E9"
    self.row_colors = ["FFFFFF", "F9F9F9"]
  end

  move_down 15
end

def payments
  @payments ||= @contractor.cpayments
                           .where(payment_date: @statement.from_date..@statement.to_date)
end

  # ================= PERIOD =================
  def period_info
    data = [
      ["From", @statement.from_date],
      ["To", @statement.to_date]
    ]

    table(data, cell_style: { borders: [] }) do
      columns(0).font_style = :bold
    end

    move_down 15
  end

  # ================= INVOICES (MATCH YOUR VIEW LOGIC) =================
  def invoices_table
    text "Invoice Breakdown", style: :bold
    move_down 8

    data = [["Invoice #", "Date", "Subtotal"]]

    invoices.each do |inv|
      data << [
        inv.invoice_number,
        inv.issue_date,
        format_currency(inv.subtotal)
      ]
    end

    table(data, header: true, width: bounds.width) do
      row(0).font_style = :bold
      row(0).background_color = "EEEEEE"
      self.row_colors = ["FFFFFF", "F9F9F9"]
    end

    move_down 15
  end

  # ================= SUMMARY (MATCH CONTROLLER LOGIC) =================
  def summary_box
    move_down 10
    text "Financial Summary", style: :bold
    move_down 10

    inv = invoices.sum(&:subtotal)
    pay = payments.sum(&:amount)
    bal = inv - pay

    data = [
      ["Total Invoiced", format_currency(inv)],
      ["Total Paid", format_currency(pay)],
      ["Balance", format_currency(bal)]
    ]

    table(data, width: bounds.width) do
      columns(0).font_style = :bold
      self.cell_style = { borders: [] }

      row(2).background_color = "FFECEC" if bal > 0
    end
  end

  # ================= DATA (MATCH CONTROLLER EXACTLY) =================
  def invoices
    @invoices ||= @contractor.cinvoices
                             .includes(:cinvoice_items)
                             .where(issue_date: @statement.from_date..@statement.to_date)
  end

  def payments
    @payments ||= @contractor.cpayments
                             .where(payment_date: @statement.from_date..@statement.to_date)
  end

  # ================= FOOTER =================
  def footer
    move_down 30
    stroke_horizontal_rule
    move_down 10

    text "Generated by Momak Technologies Ltd",
         size: 9,
         align: :center,
         style: :italic
  end

  # ================= FORMAT =================
  def format_currency(amount)
    "KES #{'%.2f' % amount.to_f}"
  end
end